#!/usr/bin/env python3
"""Materialize p101-tool-playground track docs from the wrapper graph.

The authoritative grouping lives in scripts/docs/lib-function-graph.json. This
script turns that graph into student/instructor-facing track directories inside
this playground repository.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import stat
import subprocess
from pathlib import Path
from typing import Any


# playgrounds/ now lives beside libraries/, programs/, scripts/, and templates/.
ROOT = Path(__file__).resolve().parents[1]
PLAYGROUND = Path(__file__).resolve().parent
GRAPH = ROOT / "scripts" / "docs" / "lib-function-graph.json"
TRACKS = PLAYGROUND / "tracks"

P101_LIBRARIES = [
    "p101_error",
    "p101_env",
    "p101_tool_event",
    "p101_c",
    "p101_io",
    "p101_filesystem",
    "p101_memory",
    "p101_process",
    "p101_thread",
    "p101_sync",
    "p101_ipc",
    "p101_network",
    "p101_terminal",
    "p101_time",
    "p101_identity",
    "p101_text",
    "p101_locale",
    "p101_math",
    "p101_search",
    "p101_dynamic_linking",
    "p101_diagnostics",
    "p101_database",
    "p101_cli",
    "p101_random",
    "p101_host",
    "p101_fsm",
    "p101_util",
    "p101_convert",
    "p101_c_facts",
    "m",
]

SHARED_LINKS = {
    "CMakeLists.txt": "../../CMakeLists.txt",
    "build.sh": "../../build.sh",
    "change-compiler.sh": "../../change-compiler.sh",
    "test.sh": "../../test.sh",
    "cmake": "../../cmake",
    ".flags": "../../../.flags",
    "sanitizers.txt": "../../../scripts/sanitizers.txt",
    "supported_c_compilers.txt": "../../../scripts/supported_c_compilers.txt",
}


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def load_graph() -> dict[str, Any]:
    return json.loads(GRAPH.read_text(encoding="utf-8"))


def domain_functions(graph: dict[str, Any], domain: str) -> list[str]:
    return list(graph["domains"][domain]["functions"])


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_executable(path: Path, text: str) -> None:
    write(path, text)
    mode = path.stat().st_mode
    path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def format_c(path: Path) -> None:
    formatter_name = os.environ.get("CLANG_FORMAT", "clang-format")
    formatter = shutil.which(formatter_name)
    if formatter is None:
        raise RuntimeError(f"could not find C formatter: {formatter_name}")
    subprocess.run([formatter, "-i", str(path)], check=True)


def ensure_symlink(path: Path, target: str) -> None:
    if path.is_symlink():
        if os.readlink(path) == target:
            return
        path.unlink()
    elif path.exists():
        return
    path.symlink_to(target)


def markdown_list(items: list[str]) -> str:
    if not items:
        return "- _None._"
    return "\n".join(f"- `{item}`" for item in items)


def c_string(text: str) -> str:
    return json.dumps(text)


def cmake_string(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def track_readme(graph: dict[str, Any], track: dict[str, Any], index: int) -> str:
    domains = track["domains"]
    lines = [
        f"# {track['track']}",
        "",
        "<!-- generated by ./sync-track-map.py; edit the graph/classifier, then regenerate -->",
        "",
        f"Track number: `{index:02d}`",
        "",
        f"Wrapper count: `{track['function_count']}`",
        "",
        "This directory is a standalone track project. You can enter it, build it,",
        "run it, and edit its source without depending on the top-level playground",
        "driver.",
        "",
        "```sh",
        f"cd tracks/{index:02d}-{slug(track['track'])}",
        "./run.sh",
        "./test.sh",
        "```",
        "",
        "Curated lesson guide: [TRACK.md](./TRACK.md).",
        "",
        "## Purpose",
        "",
        track["purpose"],
        "",
        "## Domains",
        "",
    ]
    lines.extend(f"- `{domain}` ({graph['domains'][domain]['count']} wrappers)" for domain in domains)
    lines.extend(
        [
            "",
            "## Suggested lesson arc",
            "",
            "1. Start with a valid, idiomatic example that uses only p101 wrappers.",
            "2. Introduce one broken fixture or commented-out trap.",
            "3. Run the playground/tooling check and read the diagnostic.",
            "4. Fix the code, re-run the check, and compare the event/report output.",
            "5. Add one regression test or corpus expectation before moving on.",
            "",
            "## Wrapper inventory",
            "",
        ]
    )
    for domain in domains:
        funcs = domain_functions(graph, domain)
        lines.extend([f"### `{domain}`", "", markdown_list(funcs), ""])
    return "\n".join(lines)


def track_lesson(track: dict[str, Any], index: int) -> str:
    if index == 0:
        return orientation_lesson()

    return "\n".join(
        [
            f"# Track {index:02d}: {track['track']}",
            "",
            "<!-- generated by ./sync-track-map.py; edit the graph/classifier, then regenerate -->",
            "",
            "## Goal",
            "",
            track["purpose"],
            "",
            "## Student workflow",
            "",
            "```sh",
            "./run.sh",
            "# inspect src/main.c and include/track_info.h",
            "./change-compiler.sh -c clang",
            "./build.sh",
            "./test.sh",
            "```",
            "",
            "Start with the valid code in `src/main.c`. Then add one small trap or",
            "exercise at a time, run the p101 tools, and fix the result before moving",
            "to the next wrapper family.",
            "",
            "## Local files",
            "",
            "- `src/main.c` — small valid program for this track.",
            "- `include/track_info.h` — generated track metadata.",
            "- `config.cmake` — local target and link configuration.",
            "- `test/CMakeLists.txt` — local smoke test for this track binary.",
            "- `run.sh` — configure/build/run convenience entry point.",
            "",
            "## Habit to practice",
            "",
            "Keep functions file-local with `static` unless they are part of the",
            "track's real API, pass `env`/`err` through code that can fail, use p101",
            "wrappers instead of direct libc/POSIX calls, and make cleanup visible.",
            "",
        ]
    )


def orientation_lesson() -> str:
    return "\n".join(
        [
            "# Track 00: p101 orientation",
            "",
            "<!-- generated by ./sync-track-map.py; edit the generator, then regenerate -->",
            "",
            "This track is the guided first walk through the p101 way of writing C.",
            "It is intentionally small. The goal is not to learn a new wrapper family",
            "yet; the goal is to understand the shape that every later track repeats.",
            "",
            "By the end, you should be able to explain:",
            "",
            "- what `struct p101_error` owns;",
            "- what `struct p101_env` configures;",
            "- why p101 wrappers receive `env` and sometimes `err`; ",
            "- how cleanup is made visible;",
            "- why direct libc/POSIX calls can make the tools blind;",
            "- what the build, test, observe, report, audit, module-map, and doctor",
            "  steps each prove.",
            "",
            "## Before you start",
            "",
            "From the repository root:",
            "",
            "```sh",
            "cd tracks/00-p101-orientation",
            "track_dir=\"$(pwd)\"",
            "workspace_root=\"$(cd ../../.. && pwd)\"",
            "```",
            "",
            "This directory is a standalone project. It has its own source, build",
            "configuration, smoke test, and runner. The expensive shared pieces",
            "(`CMakeLists.txt`, `cmake/`, flags, and helper scripts) are symlinks.",
            "",
            "## Step 1 — identify the files",
            "",
            "Open these files first:",
            "",
            "```text",
            "src/main.c",
            "include/track_info.h",
            "config.cmake",
            "test/CMakeLists.txt",
            "run.sh",
            "```",
            "",
            "What to notice:",
            "",
            "- `src/main.c` is the program students edit and reason about.",
            "- `include/track_info.h` is metadata for this track.",
            "- `config.cmake` declares the target, source files, headers, feature-test",
            "  macros, and p101 libraries.",
            "- `test/CMakeLists.txt` proves the built program runs.",
            "- `run.sh` is only convenience glue: configure if needed, build, then run.",
            "",
            "The first habit is boring but powerful: know which file is responsible for",
            "which part of the program.",
            "",
            "## Step 2 — configure and build",
            "",
            "Run:",
            "",
            "```sh",
            "./change-compiler.sh -c clang",
            "./build.sh -q",
            "```",
            "",
            "What this proves:",
            "",
            "- the compiler can see this track's local `include/` and `src/`; ",
            "- the track can find the p101 wrapper libraries;",
            "- formatting, clang-tidy, cppcheck, and static analysis all accept the",
            "  program;",
            "- generated build files stay under `build-clang/`, not mixed into source.",
            "",
            "If the build fails, read the first real diagnostic, not the final `make`",
            "line. p101 projects are intentionally strict; warnings are treated as bugs.",
            "",
            "## Step 3 — run the program",
            "",
            "Run:",
            "",
            "```sh",
            "./run.sh",
            "```",
            "",
            "The output should show the track number, purpose, and wrapper inventory.",
            "This track has wrapper count `0` because it teaches the pattern before a",
            "wrapper family is introduced.",
            "",
            "## Step 4 — read the error object setup",
            "",
            "In `src/main.c`, find:",
            "",
            "```c",
            "err = p101_error_create(false);",
            "```",
            "",
            "`err` is where fallible p101 wrappers report what went wrong. The",
            "`false` means the error object itself should not print immediately; the",
            "program decides how to handle/report the error.",
            "",
            "Then find:",
            "",
            "```c",
            "if(err == NULL)",
            "{",
            "    return EXIT_FAILURE;",
            "}",
            "```",
            "",
            "This is the one place we cannot use the p101 error object yet: if creating",
            "the error object failed, there is no error object to report through.",
            "",
            "## Step 5 — read the environment setup",
            "",
            "Now find:",
            "",
            "```c",
            "env = p101_env_create(err, NULL);",
            "```",
            "",
            "`env` is the runtime context used by wrappers and tools. It can carry",
            "tracing, observers, labels, fault-injection settings, and other behavior",
            "that plain libc calls do not know about.",
            "",
            "The second argument is the tracer. `NULL` means no default trace printing",
            "for this simple run.",
            "",
            "Immediately after creation, the program checks both the returned pointer",
            "and the error object:",
            "",
            "```c",
            "if(env == NULL || p101_error_has_error(err))",
            "{",
            "    goto done;",
            "}",
            "```",
            "",
            "That pattern matters: p101 code checks the value and the error state, then",
            "leaves through cleanup.",
            "",
            "## Step 6 — read a wrapper call",
            "",
            "Find a call like:",
            "",
            "```c",
            "p101_fprintf(env, err, stdout, \"...\");",
            "```",
            "",
            "This is a p101 wrapper around formatted output. It receives:",
            "",
            "- `env`, so observation/tracing/fault-injection can see the call;",
            "- `err`, so failures have a structured place to go;",
            "- the ordinary arguments the underlying C call needs.",
            "",
            "The important rule: if a p101 wrapper exists, use it in student code.",
            "Direct calls may work, but the p101 tools cannot see what bypasses the",
            "wrapper boundary.",
            "",
            "## Step 7 — read the helper function shape",
            "",
            "Find:",
            "",
            "```c",
            "static int write_line(const struct p101_env *env, struct p101_error *err, const char *line)",
            "```",
            "",
            "This helper is `static` because no other file needs to call it. That keeps",
            "the public API surface small. Later tracks use the same rule: put only what",
            "must be shared in headers.",
            "",
            "The helper returns `EXIT_SUCCESS` or `EXIT_FAILURE`, and it does not own",
            "`env` or `err`; it only borrows them.",
            "",
            "## Step 8 — read cleanup",
            "",
            "Find the `done:` label:",
            "",
            "```c",
            "done:",
            "    p101_env_destroy(env);",
            "    p101_error_destroy(err);",
            "    return ret_val;",
            "```",
            "",
            "This is the cleanup funnel. Later tracks use the same structure for",
            "descriptors, allocations, streams, threads, IPC objects, sockets, and FSM",
            "state.",
            "",
            "Two details are deliberate:",
            "",
            "- `ret_val` starts as failure and changes to success only after work",
            "  succeeds;",
            "- cleanup functions tolerate `NULL`, so early failure can still go through",
            "  one exit path.",
            "",
            "## Step 9 — run the smoke test",
            "",
            "Run:",
            "",
            "```sh",
            "./test.sh",
            "```",
            "",
            "This track's test is simple: it runs the built binary with CTest. That is",
            "enough for orientation because the goal is to prove the project layout and",
            "tooling loop before writing deeper unit tests.",
            "",
            "## Step 10 — observe the run",
            "",
            "Build first if needed, then run:",
            "",
            "```sh",
            "track_dir=\"$(pwd)\"",
            "workspace_root=\"$(cd ../../.. && pwd)\"",
            "build_dir=\"$(cat .last-build-dir)\"",
            "\"${workspace_root}/scripts/p101\" run \\",
            "  -o /tmp/p101-orientation-observe \\",
            "  -- \"${track_dir}/${build_dir}/p101-track-p101-orientation\"",
            "```",
            "",
            "Open the output directory:",
            "",
            "```sh",
            "ls /tmp/p101-orientation-observe",
            "```",
            "",
            "Look for:",
            "",
            "- `calls.log` — p101 call events;",
            "- `resources.log` — resource events;",
            "- `summary.txt` — quick observation summary;",
            "- `resource-report.txt` — resource lifetime result;",
            "- `trace-tree.txt` — call tree view;",
            "- `correlated-report.txt` — combined resource + call context.",
            "",
            "The key idea: p101 wrappers create an event stream. The tools analyze that",
            "stream.",
            "",
            "## Step 11 — read the report",
            "",
            "After the observe step, run:",
            "",
            "```sh",
            "sed -n '1,160p' /tmp/p101-orientation-observe/correlated-report.txt",
            "```",
            "",
            "This should be boring for the orientation program. Boring is good: a clean",
            "run teaches what normal looks like before later tracks introduce leaks,",
            "bad releases, missed wrappers, and error-path failures.",
            "",
            "## Step 12 — run wrapper audit",
            "",
            "Run:",
            "",
            "```sh",
            "track_dir=\"$(pwd)\"",
            "workspace_root=\"$(cd ../../.. && pwd)\"",
            "\"${workspace_root}/scripts/p101\" audit \"${track_dir}/src\" \"${track_dir}/include\"",
            "```",
            "",
            "The audit asks: did this code call a raw function when a p101 wrapper exists?",
            "A clean result means the rest of the wrapper-based tools can trust what they",
            "see. A direct `malloc`, `close`, `fprintf`, `pthread_*`, or similar call in",
            "student code can hide behavior from the event stream.",
            "",
            "## Step 13 — run module map",
            "",
            "Run:",
            "",
            "```sh",
            "track_dir=\"$(pwd)\"",
            "workspace_root=\"$(cd ../../.. && pwd)\"",
            "wrapper_audit=\"${workspace_root}/programs/p101-wrapper-audit/p101-wrapper-audit\"",
            "\"${workspace_root}/scripts/p101\" module-map \\",
            "  -o /tmp/p101-orientation-module-map.md \\",
            "  -F \"${wrapper_audit}\" \\",
            "  \"${track_dir}/src\" \"${track_dir}/include\"",
            "sed -n '1,200p' /tmp/p101-orientation-module-map.md",
            "```",
            "",
            "The module map asks design questions:",
            "",
            "- are too many functions public?",
            "- should helpers be `static`?",
            "- are headers exposing only what other files need?",
            "- is the project split in a teachable way?",
            "",
            "Track 00 is tiny, so this should be easy to read.",
            "",
            "## Step 14 — run the doctor",
            "",
            "Run:",
            "",
            "```sh",
            "track_dir=\"$(pwd)\"",
            "workspace_root=\"$(cd ../../.. && pwd)\"",
            "build_dir=\"$(cat .last-build-dir)\"",
            "wrapper_audit=\"${workspace_root}/programs/p101-wrapper-audit/p101-wrapper-audit\"",
            "module_map=\"${workspace_root}/programs/p101-module-map/$(cat \"${workspace_root}/programs/p101-module-map/.last-build-dir\")/p101-module-map\"",
            "\"${workspace_root}/scripts/p101\" doctor \\",
            "  -o /tmp/p101-orientation-doctor \\",
            "  -s \"${track_dir}/src\" \\",
            "  -A \"${wrapper_audit}\" \\",
            "  -M \"${module_map}\" \\",
            "  -- \"${track_dir}/${build_dir}/p101-track-p101-orientation\"",
            "```",
            "",
            "Then read:",
            "",
            "```sh",
            "sed -n '1,220p' /tmp/p101-orientation-doctor/summary.md",
            "```",
            "",
            "`p101-doctor` is the source preflight conductor. It runs the static",
            "boundary and module-shape checks, then puts the results in one place.",
            "",
            "## Step 15 — make one safe edit",
            "",
            "Add a new line of output inside `src/main.c` using `p101_fprintf`, then",
            "rerun:",
            "",
            "```sh",
            "./build.sh -q",
            "./test.sh",
            "./run.sh",
            "```",
            "",
            "Do not add raw `printf`. The point of the exercise is to practice staying",
            "inside the wrapper boundary even for simple output.",
            "",
            "## Step 16 — what to carry into Track 01",
            "",
            "Before moving on, you should be comfortable saying this out loud:",
            "",
            "1. Create `err` first.",
            "2. Create `env` with `err`.",
            "3. Use p101 wrappers for fallible work.",
            "4. Check return values and `p101_error_has_error(err)`.",
            "5. Use one cleanup path.",
            "6. Destroy `env` and `err` at the end.",
            "7. Keep helpers `static` unless another file truly needs them.",
            "8. Run build, test, observe, audit, module-map, and doctor when the lesson",
            "   asks you to prove something.",
            "",
            "That is the grammar of the rest of the playground.",
            "",
        ]
    )


def track_json(graph: dict[str, Any], track: dict[str, Any], index: int) -> str:
    data = {
        "track": track["track"],
        "title": track["track"].replace("-", " "),
        "order": index,
        "generated": True,
        "wrapper_count": track["function_count"],
        "purpose": track["purpose"],
        "domains": [
            {
                "name": domain,
                "function_count": graph["domains"][domain]["count"],
                "functions": domain_functions(graph, domain),
            }
            for domain in track["domains"]
        ],
        "local_project": {
            "source": "src/main.c",
            "header": "include/track_info.h",
            "binary": f"p101-track-{slug(track['track'])}",
        },
    }
    return json.dumps(data, indent=2) + "\n"


def track_header(track: dict[str, Any], index: int) -> str:
    guard = f"P101_TRACK_{index:02d}_{slug(track['track']).upper().replace('-', '_')}_INFO_H"
    return "\n".join(
        [
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            f"#define P101_TRACK_SLUG {c_string(track['track'])}",
            f"#define P101_TRACK_TITLE {c_string(track['track'].replace('-', ' '))}",
            f"#define P101_TRACK_PURPOSE {c_string(track['purpose'])}",
            "",
            "enum",
            "{",
            f"    P101_TRACK_INDEX         = {index},",
            f"    P101_TRACK_WRAPPER_COUNT = {track['function_count']}",
            "};",
            "",
            f"#endif /* {guard} */",
            "",
        ]
    )


def track_main(graph: dict[str, Any], track: dict[str, Any], index: int) -> str:
    functions: list[str] = []
    for domain in track["domains"]:
        functions.extend(domain_functions(graph, domain))
    if not functions:
        functions = ["none"]
    function_lines = ",\n".join(f"    {c_string(function)}" for function in functions)
    extra_includes: list[str] = []
    demo_function: list[str] = []
    demo_call: list[str] = []
    if track["track"] == "c-memory-bytes":
        extra_includes = [
            "#include <inttypes.h>",
            "#include <p101_util/endian.h>",
        ]
        demo_function = [
            "",
            "static int write_endian_demo(const struct p101_env *env, struct p101_error *err)",
            "{",
            "    const uint32_t host_value = UINT32_C(0x12345678);",
            "    uint32_t       wire_value;",
            "    uint32_t       round_trip;",
            "",
            "    wire_value = p101_htobe32(env, host_value);",
            "    round_trip = p101_be32toh(env, wire_value);",
            "    if(p101_fprintf(env, err, stdout, \"Endian round trip: 0x%08\" PRIx32 \" -> 0x%08\" PRIx32 \" -> 0x%08\" PRIx32 \"\\n\", host_value, wire_value, round_trip) < 0 || p101_error_has_error(err))",
            "    {",
            "        return EXIT_FAILURE;",
            "    }",
            "",
            "    return (round_trip == host_value) ? EXIT_SUCCESS : EXIT_FAILURE;",
            "}",
        ]
        demo_call = [
            "    if(write_endian_demo(env, err) != EXIT_SUCCESS)",
            "    {",
            "        goto done;",
            "    }",
            "",
        ]
    return "\n".join(
        [
            '#include "track_info.h"',
            "#include <p101_c/p101_stdio.h>",
            "#include <p101_c/p101_stdlib.h>",
            "#include <p101_env/env.h>",
            "#include <p101_error/error.h>",
            *extra_includes,
            "#include <stddef.h>",
            "#include <stdlib.h>",
            "",
            "static const char *const wrapper_functions[] = {",
            function_lines,
            "};",
            "",
            "static const size_t wrapper_function_count = sizeof(wrapper_functions) / sizeof(wrapper_functions[0]);",
            "",
            "static int write_line(const struct p101_env *env, struct p101_error *err, const char *line)",
            "{",
            "    int ret_val;",
            "",
            "    ret_val = p101_fprintf(env, err, stdout, \"%s\\n\", line);",
            "    if(ret_val < 0 || p101_error_has_error(err))",
            "    {",
            "        return EXIT_FAILURE;",
            "    }",
            "",
            "    return EXIT_SUCCESS;",
            "}",
            "",
            "static int write_wrapper_inventory(const struct p101_env *env, struct p101_error *err)",
            "{",
            "    int ret_val;",
            "",
            "    ret_val = EXIT_SUCCESS;",
            "    for(size_t i = 0; i < wrapper_function_count; i++)",
            "    {",
            "        if(p101_fprintf(env, err, stdout, \"- %s\\n\", wrapper_functions[i]) < 0 || p101_error_has_error(err))",
            "        {",
            "            ret_val = EXIT_FAILURE;",
            "            break;",
            "        }",
            "    }",
            "",
            "    return ret_val;",
            "}",
            *demo_function,
            "",
            "int main(void)",
            "{",
            "    struct p101_error *err;",
            "    struct p101_env   *env;",
            "    int                ret_val;",
            "",
            "    ret_val = EXIT_FAILURE;",
            "    err     = p101_error_create(false);",
            "    if(err == NULL)",
            "    {",
            "        return EXIT_FAILURE;",
            "    }",
            "",
            "    env = p101_env_create(err, NULL);",
            "    if(env == NULL || p101_error_has_error(err))",
            "    {",
            "        goto done;",
            "    }",
            "",
            "    if(p101_fprintf(env, err, stdout, \"Track %d: %s\\n\", P101_TRACK_INDEX, P101_TRACK_TITLE) < 0 || p101_error_has_error(err))",
            "    {",
            "        goto done;",
            "    }",
            "    if(write_line(env, err, P101_TRACK_PURPOSE) != EXIT_SUCCESS)",
            "    {",
            "        goto done;",
            "    }",
            "    if(p101_fprintf(env, err, stdout, \"Wrapper count: %d\\n\", P101_TRACK_WRAPPER_COUNT) < 0 || p101_error_has_error(err))",
            "    {",
            "        goto done;",
            "    }",
            "    if(write_line(env, err, \"Wrappers in this track:\") != EXIT_SUCCESS)",
            "    {",
            "        goto done;",
            "    }",
            "    if(write_wrapper_inventory(env, err) != EXIT_SUCCESS)",
            "    {",
            "        goto done;",
            "    }",
            "",
            *demo_call,
            "    ret_val = EXIT_SUCCESS;",
            "",
            "done:",
            "    p101_env_destroy(env);",
            "    p101_error_destroy(err);",
            "    return ret_val;",
            "}",
            "",
        ]
    )


def track_config(track: dict[str, Any], index: int) -> str:
    slug_text = slug(track["track"])
    link_libraries = "\n        ".join(P101_LIBRARIES)
    return "\n".join(
        [
            f'set(PROJECT_NAME "p101-track-{cmake_string(slug_text)}")',
            'set(PROJECT_VERSION "1.0.0")',
            f'set(PROJECT_DESCRIPTION "Standalone p101 playground track: {cmake_string(track["track"])}")',
            'set(PROJECT_LANGUAGE "C")',
            "",
            "set(CMAKE_C_STANDARD 17)",
            "set(CMAKE_C_STANDARD_REQUIRED ON)",
            "set(CMAKE_C_EXTENSIONS OFF)",
            "",
            "set(STANDARD_FLAGS",
            "        -D_POSIX_C_SOURCE=200809L",
            "        -D_XOPEN_SOURCE=700",
            "        -Werror",
            ")",
            "",
            "set(DARWIN_STANDARD_FLAGS",
            "        -D_DARWIN_C_SOURCE",
            ")",
            "",
            "set(LINUX_STANDARD_FLAGS)",
            "set(BSD_STANDARD_FLAGS)",
            "",
            "get_filename_component(P101_WORKSPACE_ROOT \"${CMAKE_CURRENT_SOURCE_DIR}/../../..\" ABSOLUTE)",
            "file(GLOB _P101_TRACK_LIBRARY_REPOS LIST_DIRECTORIES true \"${P101_WORKSPACE_ROOT}/libraries/lib_*\")",
            "list(SORT _P101_TRACK_LIBRARY_REPOS)",
            "set(_P101_TRACK_INCLUDE_DIRS \"\")",
            "set(_P101_TRACK_LINK_DIRS \"\")",
            "foreach (_p101_library_repo IN LISTS _P101_TRACK_LIBRARY_REPOS)",
            "    get_filename_component(_p101_library_name \"${_p101_library_repo}\" NAME)",
            "    if (_p101_library_name MATCHES \"^lib_(posix|posix_optional|posix_xsi|unix)$\")",
            "        continue()",
            "    endif ()",
            "    if (IS_DIRECTORY \"${_p101_library_repo}/include\")",
            "        list(APPEND _P101_TRACK_INCLUDE_DIRS \"${_p101_library_repo}/include\")",
            "    endif ()",
            "    if (EXISTS \"${_p101_library_repo}/.last-build-dir\")",
            "        file(READ \"${_p101_library_repo}/.last-build-dir\" _p101_last_build_dir)",
            "        string(STRIP \"${_p101_last_build_dir}\" _p101_last_build_dir)",
            "        if (IS_DIRECTORY \"${_p101_library_repo}/${_p101_last_build_dir}\")",
            "            list(APPEND _P101_TRACK_LINK_DIRS \"${_p101_library_repo}/${_p101_last_build_dir}\")",
            "        endif ()",
            "    endif ()",
            "    file(GLOB _p101_library_build_dirs LIST_DIRECTORIES true \"${_p101_library_repo}/build*\")",
            "    list(SORT _p101_library_build_dirs)",
            "    foreach (_p101_library_build_dir IN LISTS _p101_library_build_dirs)",
            "        if (IS_DIRECTORY \"${_p101_library_build_dir}\")",
            "            list(APPEND _P101_TRACK_LINK_DIRS \"${_p101_library_build_dir}\")",
            "        endif ()",
            "    endforeach ()",
            "endforeach ()",
            "list(REMOVE_DUPLICATES _P101_TRACK_INCLUDE_DIRS)",
            "list(REMOVE_DUPLICATES _P101_TRACK_LINK_DIRS)",
            "set(P101_PUBLIC_INCLUDE_DIRS \"${_P101_TRACK_INCLUDE_DIRS}\" CACHE STRING \"Track p101 include dirs\" FORCE)",
            "set(P101_PUBLIC_LINK_DIRS \"${_P101_TRACK_LINK_DIRS}\" CACHE STRING \"Track p101 link dirs\" FORCE)",
            "",
            "set(EXECUTABLE_TARGETS main)",
            "set(LIBRARY_TARGETS \"\")",
            f"set(main_OUTPUT_NAME p101-track-{slug_text})",
            "",
            "set(main_SOURCES",
            "        src/main.c",
            ")",
            "",
            "set(main_HEADERS",
            "        include/track_info.h",
            ")",
            "",
            "set(main_LINK_LIBRARIES",
            f"        {link_libraries}",
            ")",
            "",
        ]
    )


def track_test_cmake(track: dict[str, Any]) -> str:
    binary_name = f"p101-track-{slug(track['track'])}"
    return "\n".join(
        [
            "cmake_minimum_required(VERSION 3.14)",
            f"project({binary_name}-tests C)",
            "enable_testing()",
            "",
            "set(_P101_LAST_BUILD_DIR \"build-clang\")",
            "if (EXISTS \"${CMAKE_CURRENT_SOURCE_DIR}/../.last-build-dir\")",
            "    file(READ \"${CMAKE_CURRENT_SOURCE_DIR}/../.last-build-dir\" _P101_LAST_BUILD_DIR)",
            "    string(STRIP \"${_P101_LAST_BUILD_DIR}\" _P101_LAST_BUILD_DIR)",
            "endif ()",
            f"set(_P101_TRACK_BINARY \"${{CMAKE_CURRENT_SOURCE_DIR}}/../${{_P101_LAST_BUILD_DIR}}/{binary_name}\")",
            "if (NOT EXISTS \"${_P101_TRACK_BINARY}\")",
            "    message(FATAL_ERROR \"Track binary not found: ${_P101_TRACK_BINARY}. Run ../build.sh first.\")",
            "endif ()",
            "",
            "add_test(NAME track-runs COMMAND \"${_P101_TRACK_BINARY}\")",
            "",
        ]
    )


def materialize_track_project(graph: dict[str, Any], track: dict[str, Any], index: int) -> None:
    track_dir = TRACKS / f"{index:02d}-{slug(track['track'])}"
    track_dir.mkdir(parents=True, exist_ok=True)

    for name, target in SHARED_LINKS.items():
        ensure_symlink(track_dir / name, target)

    write(track_dir / "README.md", track_readme(graph, track, index))
    write(track_dir / "TRACK.md", track_lesson(track, index))
    write(track_dir / "track.json", track_json(graph, track, index))
    write(track_dir / "include" / "track_info.h", track_header(track, index))
    main_source = track_dir / "src" / "main.c"
    write(main_source, track_main(graph, track, index))
    format_c(main_source)
    write(track_dir / "config.cmake", track_config(track, index))
    write(track_dir / "test" / "CMakeLists.txt", track_test_cmake(track))
    write_executable(track_dir / "run.sh", (PLAYGROUND / "track-runner.sh").read_text(encoding="utf-8"))


def tracks_index(graph: dict[str, Any], tracks: list[dict[str, Any]]) -> str:
    repo = graph["repository_recommendation"]
    lines = [
        "# Playground tracks",
        "",
        "<!-- generated by ./sync-track-map.py; edit the graph/classifier, then regenerate -->",
        "",
        "The playground is one repository with many small tracks. The goal is to",
        "replace the old wrapper-example sprawl with focused, teachable playground",
        "areas while still covering every p101 wrapper exactly once.",
        "",
        "## Coverage",
        "",
        f"- Wrappers covered: `{repo['covered_function_count']}`",
        f"- Uncovered wrappers/domains: `{repo['uncovered_function_count']}`",
        f"- Track count: `{repo['track_count']}`",
        "- Orientation pre-track: `00-p101-orientation`",
        "- Misc tracks/domains are intentionally forbidden.",
        "",
        "## Track list",
        "",
        "| # | Track | Wrappers | Purpose |",
        "| ---: | --- | ---: | --- |",
        "| 00 | [`p101-orientation`](00-p101-orientation/README.md) | 0 | Hand-authored pre-track for env, err, wrappers, and tools. |",
    ]
    for index, track in enumerate(tracks, start=1):
        path = f"{index:02d}-{slug(track['track'])}/README.md"
        lines.append(f"| {index:02d} | [`{track['track']}`]({path}) | {track['function_count']} | {track['purpose']} |")
    lines.extend(
        [
            "",
            "## How to use this",
            "",
            "Each track directory is a standalone project with local source,",
            "metadata, build configuration, a smoke test, and a runner. A finished",
            "track should start from good examples, then add issue-focused labs",
            "where students uncomment or repair intentionally bad code and watch the",
            "checks improve.",
            "",
            "Regenerate after changing wrapper libraries or graph classification:",
            "",
            "```sh",
            "../../scripts/generators/analyze-lib-function-graph.py",
            "./sync-track-map.py",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def manifest(graph: dict[str, Any], tracks: list[dict[str, Any]]) -> str:
    data = {
        "source": str(GRAPH.relative_to(ROOT)),
        "repository": graph["repository_recommendation"]["repository"],
        "orientation_track": {
            "index": 0,
            "track": "p101-orientation",
            "directory": "00-p101-orientation",
            "function_count": 0,
            "purpose": "Hand-authored pre-track for env, err, wrappers, and tools.",
        },
        "track_count": len(tracks),
        "covered_function_count": graph["repository_recommendation"]["covered_function_count"],
        "uncovered_function_count": graph["repository_recommendation"]["uncovered_function_count"],
        "tracks": [
            {
                "index": index,
                "track": track["track"],
                "directory": f"{index:02d}-{slug(track['track'])}",
                "function_count": track["function_count"],
                "purpose": track["purpose"],
                "domains": [
                    {
                        "name": domain,
                        "function_count": graph["domains"][domain]["count"],
                        "functions": domain_functions(graph, domain),
                    }
                    for domain in track["domains"]
                ],
            }
            for index, track in enumerate(tracks, start=1)
        ],
    }
    return json.dumps(data, indent=2) + "\n"


def main() -> int:
    graph = load_graph()
    repo = graph["repository_recommendation"]
    tracks = repo["tracks"]
    if repo["uncovered_function_count"] != 0:
        raise RuntimeError("track map has uncovered wrappers/domains")
    if any("misc" in domain for domain in graph["domains"]):
        raise RuntimeError("misc domains are not allowed")

    TRACKS.mkdir(parents=True, exist_ok=True)
    write(TRACKS / "README.md", tracks_index(graph, tracks))
    write(TRACKS / "manifest.json", manifest(graph, tracks))

    orientation = {
        "track": "p101-orientation",
        "function_count": 0,
        "purpose": "Learn env/error setup, the p101 wrapper boundary, and how the playground tools report what they observe.",
        "domains": [],
    }
    materialize_track_project(graph, orientation, 0)

    for index, track in enumerate(tracks, start=1):
        materialize_track_project(graph, track, index)

    print(f"wrote {TRACKS / 'README.md'}")
    print(f"wrote {TRACKS / 'manifest.json'}")
    print(f"wrote {len(tracks) + 1} standalone track projects under {TRACKS}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
