#!/usr/bin/env python3
"""Materialize p101-tool-playground track docs from the wrapper graph.

The authoritative grouping lives in scripts/docs/lib-function-graph.json. This
script turns that graph into student/instructor-facing track directories inside
this playground repository.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
PLAYGROUND = Path(__file__).resolve().parent
GRAPH = ROOT / "scripts" / "docs" / "lib-function-graph.json"
TRACKS = PLAYGROUND / "tracks"


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def load_graph() -> dict[str, Any]:
    return json.loads(GRAPH.read_text(encoding="utf-8"))


def domain_functions(graph: dict[str, Any], domain: str) -> list[str]:
    return list(graph["domains"][domain]["functions"])


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def markdown_list(items: list[str]) -> str:
    if not items:
        return "- _None._"
    return "\n".join(f"- `{item}`" for item in items)


def track_readme(graph: dict[str, Any], track: dict[str, Any], index: int) -> str:
    domains = track["domains"]
    lines = [
        f"# {track['track']}",
        "",
        "<!-- generated by ./sync-track-map.py; edit the graph/classifier, then regenerate -->",
        "",
        f"Track number: `{index:02d}`",
        "",
        f"Wrapper count: `{track['function_count']}`",
        "",
        "## Purpose",
        "",
        track["purpose"],
        "",
        "## Domains",
        "",
    ]
    lines.extend(f"- `{domain}` ({graph['domains'][domain]['count']} wrappers)" for domain in domains)
    lines.extend(
        [
            "",
            "## Suggested lesson arc",
            "",
            "1. Start with a valid, idiomatic example that uses only p101 wrappers.",
            "2. Introduce one broken fixture or commented-out trap.",
            "3. Run the playground/tooling check and read the diagnostic.",
            "4. Fix the code, re-run the check, and compare the event/report output.",
            "5. Add one regression test or corpus expectation before moving on.",
            "",
            "## Wrapper inventory",
            "",
        ]
    )
    for domain in domains:
        funcs = domain_functions(graph, domain)
        lines.extend([f"### `{domain}`", "", markdown_list(funcs), ""])
    return "\n".join(lines)


def tracks_index(graph: dict[str, Any], tracks: list[dict[str, Any]]) -> str:
    repo = graph["repository_recommendation"]
    lines = [
        "# Playground tracks",
        "",
        "<!-- generated by ./sync-track-map.py; edit the graph/classifier, then regenerate -->",
        "",
        "The playground is one repository with many small tracks. The goal is to",
        "replace the old wrapper-example sprawl with focused, teachable playground",
        "areas while still covering every p101 wrapper exactly once.",
        "",
        "## Coverage",
        "",
        f"- Wrappers covered: `{repo['covered_function_count']}`",
        f"- Uncovered wrappers/domains: `{repo['uncovered_function_count']}`",
        f"- Track count: `{repo['track_count']}`",
        "- Misc tracks/domains are intentionally forbidden.",
        "",
        "## Track list",
        "",
        "| # | Track | Wrappers | Purpose |",
        "| ---: | --- | ---: | --- |",
    ]
    for index, track in enumerate(tracks, start=1):
        path = f"{index:02d}-{slug(track['track'])}/README.md"
        lines.append(f"| {index:02d} | [`{track['track']}`]({path}) | {track['function_count']} | {track['purpose']} |")
    lines.extend(
        [
            "",
            "## How to use this",
            "",
            "Each track directory is a planning home for labs. A finished track should",
            "contain good examples first, then issue-focused labs where students",
            "uncomment or repair intentionally bad code and watch the checks improve.",
            "",
            "Regenerate after changing wrapper libraries or graph classification:",
            "",
            "```sh",
            "../scripts/analyze-lib-function-graph.py",
            "./sync-track-map.py",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def manifest(graph: dict[str, Any], tracks: list[dict[str, Any]]) -> str:
    data = {
        "source": str(GRAPH.relative_to(ROOT)),
        "repository": graph["repository_recommendation"]["repository"],
        "track_count": len(tracks),
        "covered_function_count": graph["repository_recommendation"]["covered_function_count"],
        "uncovered_function_count": graph["repository_recommendation"]["uncovered_function_count"],
        "tracks": [
            {
                "index": index,
                "track": track["track"],
                "directory": f"{index:02d}-{slug(track['track'])}",
                "function_count": track["function_count"],
                "purpose": track["purpose"],
                "domains": [
                    {
                        "name": domain,
                        "function_count": graph["domains"][domain]["count"],
                        "functions": domain_functions(graph, domain),
                    }
                    for domain in track["domains"]
                ],
            }
            for index, track in enumerate(tracks, start=1)
        ],
    }
    return json.dumps(data, indent=2) + "\n"


def main() -> int:
    graph = load_graph()
    repo = graph["repository_recommendation"]
    tracks = repo["tracks"]
    if repo["uncovered_function_count"] != 0:
        raise RuntimeError("track map has uncovered wrappers/domains")
    if any("misc" in domain for domain in graph["domains"]):
        raise RuntimeError("misc domains are not allowed")

    TRACKS.mkdir(parents=True, exist_ok=True)
    write(TRACKS / "README.md", tracks_index(graph, tracks))
    write(TRACKS / "manifest.json", manifest(graph, tracks))
    for index, track in enumerate(tracks, start=1):
        track_dir = TRACKS / f"{index:02d}-{slug(track['track'])}"
        write(track_dir / "README.md", track_readme(graph, track, index))

    print(f"wrote {TRACKS / 'README.md'}")
    print(f"wrote {TRACKS / 'manifest.json'}")
    print(f"wrote {len(tracks)} track READMEs under {TRACKS}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
