#ifndef P101_TOOL_PLAYGROUND_ARGUMENTS_H
#define P101_TOOL_PLAYGROUND_ARGUMENTS_H

#include <stdbool.h>

enum playground_scenario
{
    SCENARIO_TOUR = 0,
    SCENARIO_CLEAN_FILE,
    SCENARIO_REALLOC,
    SCENARIO_PIPE,
    SCENARIO_FORK,
    SCENARIO_FD_LEAK,
    SCENARIO_ALLOC_LEAK,
    SCENARIO_DOUBLE_CLOSE,
    SCENARIO_STRAY_CLOSE,
    SCENARIO_FAULT_LAB,
    SCENARIO_EARLY_RETURN_FD_LEAK,
    SCENARIO_EARLY_RETURN_ALLOC_LEAK,
    SCENARIO_PARTIAL_CLEANUP,
    SCENARIO_REALLOC_LEAK,
    SCENARIO_EXEC_INHERIT,
    SCENARIO_DOUBLE_FREE,
    SCENARIO_STRAY_FREE,
    SCENARIO_SIZEOF_POINTER,
    SCENARIO_IGNORE_READ_COUNT,
    SCENARIO_UNSAFE_LOG_SECRET,
    SCENARIO_LOG_INJECTION,
    SCENARIO_MISSING_STRUCTURED_LOG,
    SCENARIO_INPUT_VALIDATION,
    SCENARIO_COMMAND_INJECTION,
    SCENARIO_PREDICTABLE_TEMP_FILE,
    SCENARIO_SIGNED_CONVERSION,
    SCENARIO_TRUNCATION,
    SCENARIO_USE_AFTER_FREE,
    SCENARIO_REALLOC_FAILURE,
    SCENARIO_OUT_OF_BOUNDS_WRITE,
    SCENARIO_OUT_OF_BOUNDS_READ,
    SCENARIO_BUFFER_OVERFLOW,
    SCENARIO_UNINITIALIZED_READ,
    SCENARIO_NULL_DEREFERENCE,
    SCENARIO_INTEGER_OVERFLOW,
    SCENARIO_PATH_TRAVERSAL,
    SCENARIO_FORMAT_STRING,
    SCENARIO_STALE_SECRET,
    SCENARIO_RESOURCE_EXHAUSTION,
    SCENARIO_TOCTOU,
    SCENARIO_DATA_RACE,
    SCENARIO_STRING_NOT_TERMINATED,
    SCENARIO_PARTIAL_WRITE,
    SCENARIO_INTERRUPTED_SYSCALL,
    SCENARIO_UNSAFE_FILE_MODE,
    SCENARIO_SYMLINK_FOLLOW,
    SCENARIO_TRUSTED_ENVIRONMENT,
    SCENARIO_UNCHECKED_PARSE,
    SCENARIO_MISSING_AUTHORIZATION,
    SCENARIO_CLEANUP_ORDER,
    SCENARIO_THREAD_ARGUMENT_LIFETIME,
    SCENARIO_SHORT_READ,
    SCENARIO_READ_EOF_HANDLING,
    SCENARIO_PARSER_FUZZ,
    SCENARIO_C_MEMORY_RUNTIME
};

struct arguments
{
    const char              *scenario_str;
    const char              *output_path;
    const char              *bytes_str;
    const char              *repeats_str;
    enum playground_scenario scenario;
    unsigned int             bytes;
    unsigned int             repeats;
    bool                     verbose;
};

#endif    // P101_TOOL_PLAYGROUND_ARGUMENTS_H
